version: "3.9"
services:
  crt_sh:
    build: ./crt_sh
    container_name: "crt_sh"
    volumes:
      - ./treasure/crt_sh:/crt_sh
    command: [ "crt_sh.sh", "${target}" ]
  sublist3r:
    build: ./sublist3r
    container_name: "sublist3r"
    volumes:
      - ./treasure/sublist3r:/sublist3r
    command: [ "sublist3r.sh", "${target}" ]
  assetfinder:
    build: ./assetfinder
    container_name: "assetfinder"
    volumes:
      - ./treasure/assetfinder:/assetfinder
    command: [ "assetfinder.sh", "${target}" ]
  subfinder:
    build: ./subfinder
    container_name: "subfinder"
    volumes:
      - ./treasure/subfinder:/subfinder
    command: ["subfinder.sh", "${target}" ]
  amass:
    build: ./amass
    container_name: "amass"
    volumes:
      - ./treasure/amass:/amass
    command: ["amass.sh", "${target}" ]
