version: "3.9"
services:
  nmap_full_tcp:
    build: ./nmap
    container_name: "nmap_full_tcp"
    volumes:
      - ./treasure/nmap:/nmap
    command: [ "nmap_full_tcp.sh"]
  nmap_quick_tcp:
    build: ./nmap
    container_name: "nmap_quick_tcp"
    volumes:
      - ./treasure/nmap:/nmap
    command: [ "nmap_quick_tcp.sh"]