version: "3.9"
services:
  gau:
    build: ./gau
    container_name: "gau"
    volumes:
      - ./treasure/gau:/gau
    command: [ "gau.sh" ]
  waybackurls:
    build: ./waybackurls
    container_name: "waybackurls"
    volumes:
      - ./treasure/waybackurls:/waybackurls
    command: [ "waybackurls.sh" ]