version: "3.9"
services:
  dnsrecon:
    build: ./dnsrecon
    container_name: "dnsrecon"
    volumes:
      - ./treasure/dnsrecon:/dnsrecon
    command: [ "dnsrecon.sh"]
  dig:
    build: ./dig
    container_name: "dig"
    volumes:
      - ./treasure/dig:/dig
    command: [ "dig.sh"]