version: "3.9"
services:
  python3:
    build: ./python3
    container_name: "python3"
    command: [ "target.py", "${target}" ]
  #################################################
  # find subdomain
  #################################################
  altdns:
    build: ./altdns
    container_name: "altdns"
    volumes:
      - ./treasure/altdns:/altdns
    command: ["altdns.sh", "${target}" ]
  assetfinder:
    build: ./assetfinder
    container_name: "assetfinder"
    volumes:
      - ./treasure/assetfinder:/assetfinder
    command: [ "assetfinder.sh", "${target}" ]
  subfinder:
    build: ./subfinder
    container_name: "subfinder"
    volumes:
      - ./treasure/subfinder:/subfinder
    command: ["subfinder.sh", "${target}" ]
  amass:
    build: ./amass
    container_name: "amass"
    volumes:
      - ./treasure/amass:/amass
    command: ["amass.sh", "${target}" ]
